server.port=8888

spring.application.name=config-server


spring.profiles.active=git


spring.cloud.config.server.git.uri=https://github.com/DzMaks/user-platform.git

spring.cloud.config.server.git.default-label=feature/notification-service

spring.cloud.config.server.git.search-paths=config-repo

spring.cloud.config.server.git.clone-on-start=true



eureka.client.register-with-eureka=false

eureka.client.fetch-registry=false